### ISSUE TITLE
Notification is not triggered when the cell has an error.

### ISSUE THREAD

**Issue by i-aki-y** [mwakaba2/jupyterlab-notifications#10]
In the current implementation, notification is triggered by `NotebookActions.executed` signal. Unfortunately, this signal seems not to be emitted when the cell has any exceptions.

Although I don't have any idea how to fix the issue, I think it's natural to want to know as soon as possible when an error occurs.

## example

I set notification threshold 3 sec:

```
{
    "minimum_cell_execution_time": 3,
}
```

And, I confirmed that the following code worked.

```
!sleep 3
print("hello world!")
```

With the same configuration, I tried the following code.

```
!sleep 3
raise ValueError("fail")
```

**Comment by mwakaba2** [comment]
Thanks for reporting this @i-aki-y ! I'll reproduce this today and look into some possible solutions.

**Comment by mwakaba2** [comment]
It looks like I'll need to make a PR to jupyterlab to emit the signal from the failed notebook cell, so this might take some time to fix. 

Currently, jupyterlab only emits a signal when the notebook cell was successfully executed. ([code](https://github.com/jupyterlab/jupyterlab/blob/765ee24f8923b907dc2a3a6cf158ca40f3e9fab7/packages/notebook/src/actions.tsx#L1642))

The fix should be simple. I can emit the signal for both failed/succeeded cell, create a new attribute `status` in the code cell metadata, and display an error message based on that, but I'll want to check with the Jupyterlab team if that's a proper fix. 
```javascript
if (reply.content.status === 'ok') {
 ....
  cell.model.metadata.set('status', 'ok');
  return true;
} 
else if (reply.content.status == 'error') {
  cell.model.metadata.set('status', 'error');
   return true;
} ....
...
.then(ran => {
  if (ran) {
    executed.emit({ notebook, cell });
 }

  return ran;
});
```

**Comment by i-aki-y** [comment]
Although I am not sure why jupyterlab does not emit `executed` signal when the error has happened, your approach sounds good. Especially, success / error status seems to be useful information for the notification purpose.

**Comment by mwakaba2** [comment]
@i-aki-y I made a [PR](https://github.com/jupyterlab/jupyterlab/pull/10493) to jupyterlab to return the executed signal for both successful and failed executions. I'll get a PR out this week to fix this issue.
