### ISSUE TITLE
Cell number mismatch?

### ISSUE THREAD

**Issue by i-aki-y** [mwakaba2/jupyterlab-notifications#12]
I found the cell number displayed in the notification message does not match the cell number of the notebook.
It looks that the `notebook.activeCellIndex` returns the position and does not care about the number of execution.

See the following image (captured from the readme page):

![cell-number-mismatch](https://user-images.githubusercontent.com/9190086/117602720-58e6f180-b18c-11eb-9f82-88be1411dfac.jpg)

**Comment by mwakaba2** [comment]
Hi @i-aki-y, thanks again for creating an issue, but this is a design choice I made intentionally. 
I chose to display the cell number (=position) instead of the execution count, because I think the position gives a more accurate picture of the notebook execution progress. However, if the execution count info is valuable, that can be made configurable.

**Comment by i-aki-y** [comment]
@mwakaba2  Thank you for your quick response and clarification.
I understand your intentions.
According to your suggestion to introduce `report_cell_execution_count`, I want to revise my PR.

**Comment by i-aki-y** [comment]
@mwakaba2  Can I have your advice about this issue?

Suppose I introduce a new configuration (`report_execution_count`). In that case, I think one of the "cell index" or "execution count" should be valid because it would be redundant and somewhat confusing to display both of them.

So I think to introduce a different configuration like `cell_number_type` with options "cell_index" and "cell_execution_count".
And the `executionCount` would be displayed when the "cell_execution_count" is selected.

The settings will become like this:

```
{
    ....
    // Report Notebook Cell Number
    // Display notebook cell number in the notification.
    "report_cell_number": true,

    // Cell Number Type
    // Type of cell number to display when the report_cell_number is true. Select from 'cell_index' or ‘cell_execution_count'.
    "cell_number_type": "cell_index",
}

```

If there seems to be no problem, I would like to fix my PR by this approach.

**Comment by mwakaba2** [comment]
@i-aki-y Yeah I agree showing one or the other would suffice. This sounds like a great approach. 🙂
