### ISSUE TITLE
The `cellStartTime` is overwritten with multiple executions.

### ISSUE THREAD

**Issue by i-aki-y** [mwakaba2/jupyterlab-notifications#23]
Thanks to introducing the `executionScheduled` signal, we can now calculate the duration time more flexibly.
But in the current version, the `cellStartTime` is shared between multiple cell executions, so the `cellStartTime` can be overwritten by the latest execution.
This might cause some unexpected behaviors, see the following example.

### Example

Now, let assume the following settings and cells:

```
# settings
{
    "minimum_cell_execution_time": 3,
}
```

```
# cells
Cell [1]: !sleep 4
Cell [2]: !sleep 2
````

Consider running the two cells in the following steps:

1. run the cell [1].
2. wait 2 seconds.
3. run the cell [2].
 
In this case, I expect that a notification is issued just after completing the cell [1]. But no notification is given because the cell [2] execution overwrites the `cellStartTime` and the duration time of the cell [1] becomes to be less than 2 seconds.

### Workaround idea

I think a simple workaround is to introduce a table that has mappings from cells to their cellStartTimes and replace `cellStartTime` with `cellStartTimeTable[cell.id]` or something.
Note this is a just idea, so there may be non-trivial problems.

**Comment by mwakaba2** [comment]
Yeah, I think you're right. Thank you for spotting this!
Using a table to keep track of the cell start time states sounds like a good idea. 
I'm assuming the `cell.id`s are unique, so we won't need to prepend the cell id with a notebook name in the case when users are running multiple notebooks at the same time. 
Also after the notification successfully gets triggered for a particular cell, the associated key/value pair can be deleted from the table. 
I'll think a little more about this option and possibly some other options as well over this weekend. 
Thanks again for reporting this! 🙂
