### ISSUE TITLE
The binder link in the readme points to a non-existing notebook

### ISSUE THREAD

**Issue by krassowski** [mwakaba2/jupyterlab-notifications#26]
The link to binder is: https://mybinder.org/v2/gh/mwakaba2/jupyterlab-notifications/main?urlpath=/lab/tree/demo.ipynb but there is no `demo.ipynb` notebook (but there are some notebooks in `tutorial`). I think it would be good to update the link to point to one of the notebooks in `tutorial` directory, or to create a README.md in `tutorial` and point to it.

**Comment by mwakaba2** [comment]
Thanks for catching that! I fixed the binder link to point to the `py3_demo.ipynb` notebook in the tutorial directory. 
I also included some instructions and comments in the `tutorial` notebooks.

**Comment by krassowski** [comment]
Thank you!
