### ISSUE TITLE
Source archive on PyPI to bring package to conda-forge

### ISSUE THREAD

**Issue by m-rossi** [mwakaba2/jupyterlab-notifications#29]
Hey, thank you for your great package, I find it really useful for various of my tasks, especially the settings `last_cell_only` and `minimum_cell_execution_time` compared to previous attempts of notifications in Jupyter/JupyterLab.

Therefore I would like to add your package to [conda-forge](https://conda-forge.org) for easier usage with the [conda](https://docs.conda.io/en/latest/)-package manager popular in data science. However to do that, it is required to have the source archive (`tar.gz`) including the license to PyPI. Could you add that?

**Comment by mwakaba2** [comment]
Hi @m-rossi , thank you for using this extension, and I'm glad the settings are useful!
Of course! I'm not familiar with adding packages to conda-forge, so your help would be great.

I just published a new version 0.3.3 and pushed a source archive and wheel to PyPI. License.txt should be included. 
https://pypi.org/project/jupyterlab-notifications/0.3.3/#files

**Comment by m-rossi** [comment]
Thanks! I will try to add the recipe tomorrow.
