### ISSUE TITLE
Safari compatibility

### ISSUE THREAD

**Issue by tysun** [mwakaba2/jupyterlab-notifications#36]
Works well in Chrome, so it does what Colab does which is good, but is there anyway we can get this working in Safari? 
Also I noticed that the notifications even in Chrome macOS are silent even though I've enabled sound. Is this a developer choice or Chrome/macOS limitation?

Thanks

**Comment by i-aki-y** [comment]
Hi, @tysun I am also using macOS (Monterey), and both safari and chrome are working fine.
If you could get notifications from colab but could not get from your jupyterlab, I guess that the browser does not allow notifications from your jupyterlab's URL (ex. localhost:8888).

For sound, I also could not make it work (Colab too).
The notification is implemented by using Notifications API (https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) with default parameters (this includes silent = false), it would allow sound. Although I am not sure why this does not work, I think it is a limitation of the OS or browser side.
