### ISSUE TITLE
Notification is blocked by chrome

### ISSUE THREAD

**Issue by Betristor** [mwakaba2/jupyterlab-notifications#37]
I set up a jupyterlab service on remote machine and access it on the go. But after I installed the extension successfully, it keeps pushing **Browser Notifications are not allowed. Please update your browser settings to allow notifications**. I enabled chrome to allow my ip to send notification but nothing changed.

I'm sure it's the problem of chrome, but I don't know where the problem is, remote chrome or local chrome?

Chrome version: 99.0.4844.84 on M1.
Remote: ubuntu 20.04 with jupyterlab 3.3.2.
BTW I started the lab service under jupyterhub.

**Comment by i-aki-y** [comment]
@Betristor Are not you using HTTP instead of HTTPS to access your remote jupyterlab?
As far as I know, Notification API requires HTTPS connection except for localhost.

**Comment by Betristor** [comment]
Yes, that's the situation I'm in. I'm using a local network, so i'm not bothering to enable https. Much thanks!

**Comment by jianjiangant** [comment]
type " chrome://flags/#unsafely-treat-insecure-origin-as-secure and " in address bar and enable it by pass your jupyterlab url
