### ISSUE TITLE
JupyterLab 4 / Jupter Notebook 7 support

### ISSUE THREAD

**Issue by m-rossi** [mwakaba2/jupyterlab-notifications#39]
Hey @mwakaba2 I wanted to kindly ask if you could add support for JupyterLab 4 / Jupyter Notebook 7. They have been both released a few days ago and prevent my Python environment from updating.

**Comment by mwakaba2** [comment]
@m-rossi thanks for creating this issue, and apologies for the delay! We just merged @i-aki-y PR to support Jupyterlab 4, so we're thinking about publishing it to PYPI sometime this week.

**Comment by m-rossi** [comment]
Just merged https://github.com/conda-forge/jupyterlab-notifications-feedstock/pull/7, should be available soon. Thanks @mwakaba2  and @i-aki-y!
